// <auto-generated />
using System;
using CollectorsApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectorsApp.DAL.Migrations
{
    [DbContext(typeof(CollectorsAppDbContext))]
    partial class CollectorsAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CollectorsApp.DAL.Entities.Collectible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BoughtFor")
                        .HasColumnType("int");

                    b.Property<bool>("ForSale")
                        .HasColumnType("bit");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("CollectorsApp.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("AttackingRating")
                        .HasColumnType("float");

                    b.Property<double>("ClubWorth")
                        .HasColumnType("float");

                    b.Property<double>("DefenceDepth")
                        .HasColumnType("float");

                    b.Property<double>("DefenceRating")
                        .HasColumnType("float");

                    b.Property<double>("DefenceWidth")
                        .HasColumnType("float");

                    b.Property<double>("Dislikes")
                        .HasColumnType("float");

                    b.Property<double>("Likes")
                        .HasColumnType("float");

                    b.Property<int>("Matches_played")
                        .HasColumnType("int");

                    b.Property<double>("MidfieldRating")
                        .HasColumnType("float");

                    b.Property<double>("OffenceWidth")
                        .HasColumnType("float");

                    b.Property<double>("Overall")
                        .HasColumnType("float");

                    b.Property<string>("Teamname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("XIAverageAge")
                        .HasColumnType("float");

                    b.Property<double>("avGoalDiff")
                        .HasColumnType("float");

                    b.Property<double>("avblockedshots")
                        .HasColumnType("float");

                    b.Property<double>("avconceded")
                        .HasColumnType("float");

                    b.Property<double>("avdraws")
                        .HasColumnType("float");

                    b.Property<double>("avfreekicks")
                        .HasColumnType("float");

                    b.Property<double>("avgoalattempts")
                        .HasColumnType("float");

                    b.Property<double>("avgoals")
                        .HasColumnType("float");

                    b.Property<double>("avloses")
                        .HasColumnType("float");

                    b.Property<double>("avpossession")
                        .HasColumnType("float");

                    b.Property<double>("avshotsoffgoal")
                        .HasColumnType("float");

                    b.Property<double>("avshotsongoal")
                        .HasColumnType("float");

                    b.Property<double>("avwins")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackingRating = 75.0,
                            ClubWorth = 13.0,
                            DefenceDepth = 30.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 50.0,
                            Dislikes = 15.0,
                            Likes = 45.0,
                            Matches_played = 190,
                            MidfieldRating = 73.0,
                            OffenceWidth = 70.0,
                            Overall = 74.0,
                            Teamname = "Alaves",
                            XIAverageAge = 28.640000000000001,
                            avGoalDiff = 0.28947368421052599,
                            avblockedshots = 2.1631578947368402,
                            avconceded = 1.3631578947368399,
                            avdraws = 0.24210526315789499,
                            avfreekicks = 15.526315789473699,
                            avgoalattempts = 9.8315789473684205,
                            avgoals = 1.0,
                            avloses = 0.43684210526315798,
                            avpossession = 42.073684210526302,
                            avshotsoffgoal = 4.5263157894736796,
                            avshotsongoal = 3.1421052631578901,
                            avwins = 0.32105263157894698
                        },
                        new
                        {
                            Id = 2,
                            AttackingRating = 73.0,
                            ClubWorth = 150.0,
                            DefenceDepth = 37.0,
                            DefenceRating = 71.0,
                            DefenceWidth = 45.0,
                            Dislikes = 5.0,
                            Likes = 32.0,
                            Matches_played = 76,
                            MidfieldRating = 70.0,
                            OffenceWidth = 54.0,
                            Overall = 72.0,
                            Teamname = "Almeria",
                            XIAverageAge = 25.18,
                            avGoalDiff = 0.40789473684210498,
                            avblockedshots = 2.3815789473684199,
                            avconceded = 1.7763157894736801,
                            avdraws = 0.197368421052632,
                            avfreekicks = 15.2631578947368,
                            avgoalattempts = 10.407894736842101,
                            avgoals = 1.0263157894736801,
                            avloses = 0.55263157894736903,
                            avpossession = 43.868421052631597,
                            avshotsoffgoal = 4.5526315789473699,
                            avshotsongoal = 3.4736842105263199,
                            avwins = 0.25
                        },
                        new
                        {
                            Id = 3,
                            AttackingRating = 80.0,
                            ClubWorth = 250.0,
                            DefenceDepth = 50.0,
                            DefenceRating = 78.0,
                            DefenceWidth = 50.0,
                            Dislikes = 31.0,
                            Likes = 148.0,
                            Matches_played = 304,
                            MidfieldRating = 79.0,
                            OffenceWidth = 70.0,
                            Overall = 78.0,
                            Teamname = "Ath_Bilbao",
                            XIAverageAge = 27.640000000000001,
                            avGoalDiff = 0.47368421052631599,
                            avblockedshots = 2.4342105263157898,
                            avconceded = 1.125,
                            avdraws = 0.28289473684210498,
                            avfreekicks = 16.351973684210499,
                            avgoalattempts = 11.598684210526301,
                            avgoals = 1.2763157894736801,
                            avloses = 0.32565789473684198,
                            avpossession = 50.789473684210499,
                            avshotsoffgoal = 5.0394736842105301,
                            avshotsongoal = 4.125,
                            avwins = 0.39144736842105299
                        },
                        new
                        {
                            Id = 4,
                            AttackingRating = 84.0,
                            ClubWorth = 1200.0,
                            DefenceDepth = 60.0,
                            DefenceRating = 83.0,
                            DefenceWidth = 60.0,
                            Dislikes = 113.0,
                            Likes = 400.0,
                            Matches_played = 303,
                            MidfieldRating = 84.0,
                            OffenceWidth = 40.0,
                            Overall = 84.0,
                            Teamname = "Atl_Madrid",
                            XIAverageAge = 27.91,
                            avGoalDiff = 0.39933993399339901,
                            avblockedshots = 2.56435643564356,
                            avconceded = 0.66996699669966997,
                            avdraws = 0.23432343234323399,
                            avfreekicks = 13.891089108910901,
                            avgoalattempts = 12.1353135313531,
                            avgoals = 1.67656765676568,
                            avloses = 0.13531353135313501,
                            avpossession = 49.046204620462099,
                            avshotsoffgoal = 4.9537953795379499,
                            avshotsongoal = 4.6171617161716201,
                            avwins = 0.63036303630363
                        },
                        new
                        {
                            Id = 5,
                            AttackingRating = 81.0,
                            ClubWorth = 3200.0,
                            DefenceDepth = 80.0,
                            DefenceRating = 80.0,
                            DefenceWidth = 60.0,
                            Dislikes = 541.0,
                            Likes = 1449.0,
                            Matches_played = 304,
                            MidfieldRating = 84.0,
                            OffenceWidth = 30.0,
                            Overall = 83.0,
                            Teamname = "Barcelona",
                            XIAverageAge = 25.09,
                            avGoalDiff = 0.457236842105263,
                            avblockedshots = 3.32894736842105,
                            avconceded = 0.85855263157894701,
                            avdraws = 0.17105263157894701,
                            avfreekicks = 16.842105263157901,
                            avgoalattempts = 15.605263157894701,
                            avgoals = 2.625,
                            avloses = 0.115131578947368,
                            avpossession = 66.226973684210506,
                            avshotsoffgoal = 5.4802631578947398,
                            avshotsongoal = 6.7960526315789496,
                            avwins = 0.71381578947368396
                        },
                        new
                        {
                            Id = 6,
                            AttackingRating = 79.0,
                            ClubWorth = 175.0,
                            DefenceDepth = 70.0,
                            DefenceRating = 77.0,
                            DefenceWidth = 60.0,
                            Dislikes = 49.0,
                            Likes = 165.0,
                            Matches_played = 266,
                            MidfieldRating = 80.0,
                            OffenceWidth = 60.0,
                            Overall = 79.0,
                            Teamname = "Betis",
                            XIAverageAge = 30.27,
                            avGoalDiff = 0.360902255639098,
                            avblockedshots = 2.9172932330827099,
                            avconceded = 1.56766917293233,
                            avdraws = 0.23684210526315799,
                            avfreekicks = 17.657894736842099,
                            avgoalattempts = 11.699248120300799,
                            avgoals = 1.1766917293233099,
                            avloses = 0.43984962406014999,
                            avpossession = 53.428571428571402,
                            avshotsoffgoal = 4.6766917293233101,
                            avshotsongoal = 4.1052631578947398,
                            avwins = 0.32330827067669199
                        },
                        new
                        {
                            Id = 7,
                            AttackingRating = 76.0,
                            ClubWorth = 3.5,
                            DefenceDepth = 50.0,
                            DefenceRating = 73.0,
                            DefenceWidth = 70.0,
                            Dislikes = 8.0,
                            Likes = 31.0,
                            Matches_played = 38,
                            MidfieldRating = 74.0,
                            OffenceWidth = 80.0,
                            Overall = 74.0,
                            Teamname = "Cadiz_CF",
                            XIAverageAge = 27.73,
                            avGoalDiff = -0.105263157894737,
                            avblockedshots = 1.15789473684211,
                            avconceded = 1.5263157894736801,
                            avdraws = 0.28947368421052599,
                            avfreekicks = 17.421052631578899,
                            avgoalattempts = 8.0,
                            avgoals = 0.94736842105263197,
                            avloses = 0.42105263157894701,
                            avpossession = 34.2368421052632,
                            avshotsoffgoal = 4.1578947368421098,
                            avshotsongoal = 2.6842105263157898,
                            avwins = 0.28947368421052599
                        },
                        new
                        {
                            Id = 8,
                            AttackingRating = 80.0,
                            ClubWorth = 110.0,
                            DefenceDepth = 60.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 70.0,
                            Dislikes = 11.0,
                            Likes = 62.0,
                            Matches_played = 304,
                            MidfieldRating = 76.0,
                            OffenceWidth = 40.0,
                            Overall = 76.0,
                            Teamname = "Celta_Vigo",
                            XIAverageAge = 28.449999999999999,
                            avGoalDiff = 0.355263157894737,
                            avblockedshots = 2.7302631578947398,
                            avconceded = 1.4934210526315801,
                            avdraws = 0.269736842105263,
                            avfreekicks = 15.608552631579,
                            avgoalattempts = 11.3684210526316,
                            avgoals = 1.32894736842105,
                            avloses = 0.39802631578947401,
                            avpossession = 54.042763157894697,
                            avshotsoffgoal = 4.5296052631579,
                            avshotsongoal = 4.1085526315789496,
                            avwins = 0.332236842105263
                        },
                        new
                        {
                            Id = 9,
                            AttackingRating = 72.0,
                            ClubWorth = 12.6,
                            DefenceDepth = 38.0,
                            DefenceRating = 70.0,
                            DefenceWidth = 52.0,
                            Dislikes = 0.0,
                            Likes = 9.0,
                            Matches_played = 38,
                            MidfieldRating = 71.0,
                            OffenceWidth = 59.0,
                            Overall = 71.0,
                            Teamname = "Cordoba",
                            XIAverageAge = 25.359999999999999,
                            avGoalDiff = 0.105263157894737,
                            avblockedshots = 2.1842105263157898,
                            avconceded = 1.7894736842105301,
                            avdraws = 0.28947368421052599,
                            avfreekicks = 16.315789473684202,
                            avgoalattempts = 10.394736842105299,
                            avgoals = 0.57894736842105299,
                            avloses = 0.63157894736842102,
                            avpossession = 46.368421052631597,
                            avshotsoffgoal = 5.0,
                            avshotsongoal = 3.2105263157894699,
                            avwins = 0.078947368421052599
                        },
                        new
                        {
                            Id = 10,
                            AttackingRating = 79.0,
                            ClubWorth = 100.0,
                            DefenceDepth = 47.0,
                            DefenceRating = 77.0,
                            DefenceWidth = 66.0,
                            Dislikes = 11.0,
                            Likes = 61.0,
                            Matches_played = 152,
                            MidfieldRating = 77.0,
                            OffenceWidth = 78.0,
                            Overall = 77.0,
                            Teamname = "Dep_La_Coruna",
                            XIAverageAge = 29.09,
                            avGoalDiff = 0.32236842105263203,
                            avblockedshots = 2.6578947368421102,
                            avconceded = 1.6973684210526301,
                            avdraws = 0.36184210526315802,
                            avfreekicks = 15.532894736842101,
                            avgoalattempts = 11.664473684210501,
                            avgoals = 1.05921052631579,
                            avloses = 0.44736842105263203,
                            avpossession = 47.190789473684198,
                            avshotsoffgoal = 5.25,
                            avshotsongoal = 3.7565789473684199,
                            avwins = 0.19078947368421101
                        },
                        new
                        {
                            Id = 11,
                            AttackingRating = 76.0,
                            ClubWorth = 29.0,
                            DefenceDepth = 80.0,
                            DefenceRating = 74.0,
                            DefenceWidth = 50.0,
                            Dislikes = 8.0,
                            Likes = 34.0,
                            Matches_played = 266,
                            MidfieldRating = 75.0,
                            OffenceWidth = 60.0,
                            Overall = 76.0,
                            Teamname = "Eibar",
                            XIAverageAge = 28.550000000000001,
                            avGoalDiff = 0.37593984962406002,
                            avblockedshots = 2.61278195488722,
                            avconceded = 1.40977443609023,
                            avdraws = 0.266917293233083,
                            avfreekicks = 14.462406015037599,
                            avgoalattempts = 11.687969924812,
                            avgoals = 1.1165413533834601,
                            avloses = 0.44360902255639101,
                            avpossession = 48.289473684210499,
                            avshotsoffgoal = 5.1992481203007497,
                            avshotsongoal = 3.8759398496240598,
                            avwins = 0.28947368421052599
                        },
                        new
                        {
                            Id = 12,
                            AttackingRating = 76.0,
                            ClubWorth = 4.7999999999999998,
                            DefenceDepth = 50.0,
                            DefenceRating = 73.0,
                            DefenceWidth = 50.0,
                            Dislikes = 3.0,
                            Likes = 23.0,
                            Matches_played = 114,
                            MidfieldRating = 75.0,
                            OffenceWidth = 50.0,
                            Overall = 75.0,
                            Teamname = "Elche",
                            XIAverageAge = 29.0,
                            avGoalDiff = 0.31578947368421101,
                            avblockedshots = 1.9912280701754399,
                            avconceded = 1.4649122807017501,
                            avdraws = 0.28947368421052599,
                            avfreekicks = 16.157894736842099,
                            avgoalattempts = 9.4736842105263204,
                            avgoals = 0.86842105263157898,
                            avloses = 0.464912280701754,
                            avpossession = 47.543859649122801,
                            avshotsoffgoal = 4.4736842105263204,
                            avshotsongoal = 3.0087719298245599,
                            avwins = 0.24561403508771901
                        },
                        new
                        {
                            Id = 13,
                            AttackingRating = 78.0,
                            ClubWorth = 60.0,
                            DefenceDepth = 50.0,
                            DefenceRating = 76.0,
                            DefenceWidth = 60.0,
                            Dislikes = 28.0,
                            Likes = 75.0,
                            Matches_played = 266,
                            MidfieldRating = 77.0,
                            OffenceWidth = 60.0,
                            Overall = 77.0,
                            Teamname = "Espanyol",
                            XIAverageAge = 28.0,
                            avGoalDiff = 0.30827067669172897,
                            avblockedshots = 2.4511278195488702,
                            avconceded = 1.4135338345864701,
                            avdraws = 0.266917293233083,
                            avfreekicks = 15.853383458646601,
                            avgoalattempts = 10.609022556391,
                            avgoals = 1.0827067669172901,
                            avloses = 0.42481203007518797,
                            avpossession = 46.154135338345903,
                            avshotsoffgoal = 4.5075187969924801,
                            avshotsongoal = 3.6503759398496198,
                            avwins = 0.30827067669172897
                        },
                        new
                        {
                            Id = 14,
                            AttackingRating = 75.0,
                            ClubWorth = 45.0,
                            DefenceDepth = 70.0,
                            DefenceRating = 76.0,
                            DefenceWidth = 40.0,
                            Dislikes = 21.0,
                            Likes = 50.0,
                            Matches_played = 266,
                            MidfieldRating = 77.0,
                            OffenceWidth = 70.0,
                            Overall = 76.0,
                            Teamname = "Getafe",
                            XIAverageAge = 26.18,
                            avGoalDiff = 0.46240601503759399,
                            avblockedshots = 2.53383458646617,
                            avconceded = 1.25187969924812,
                            avdraws = 0.27067669172932302,
                            avfreekicks = 16.560150375939799,
                            avgoalattempts = 10.6278195488722,
                            avgoals = 1.0,
                            avloses = 0.41729323308270699,
                            avpossession = 43.345864661654097,
                            avshotsoffgoal = 4.6278195488721803,
                            avshotsongoal = 3.46616541353383,
                            avwins = 0.31203007518796999
                        },
                        new
                        {
                            Id = 15,
                            AttackingRating = 75.0,
                            ClubWorth = 17.0,
                            DefenceDepth = 45.0,
                            DefenceRating = 73.0,
                            DefenceWidth = 41.0,
                            Dislikes = 6.0,
                            Likes = 24.0,
                            Matches_played = 76,
                            MidfieldRating = 73.0,
                            OffenceWidth = 43.0,
                            Overall = 74.0,
                            Teamname = "Gijon",
                            XIAverageAge = 25.449999999999999,
                            avGoalDiff = 0.36842105263157898,
                            avblockedshots = 2.3684210526315801,
                            avconceded = 1.76315789473684,
                            avdraws = 0.25,
                            avfreekicks = 14.5,
                            avgoalattempts = 9.8026315789473699,
                            avgoals = 1.07894736842105,
                            avloses = 0.52631578947368396,
                            avpossession = 43.7631578947368,
                            avshotsoffgoal = 4.0526315789473699,
                            avshotsongoal = 3.3815789473684199,
                            avwins = 0.22368421052631601
                        },
                        new
                        {
                            Id = 16,
                            AttackingRating = 79.0,
                            ClubWorth = 9.8000000000000007,
                            DefenceDepth = 50.0,
                            DefenceRating = 76.0,
                            DefenceWidth = 40.0,
                            Dislikes = 8.0,
                            Likes = 38.0,
                            Matches_played = 76,
                            MidfieldRating = 76.0,
                            OffenceWidth = 40.0,
                            Overall = 77.0,
                            Teamname = "Girona",
                            XIAverageAge = 25.91,
                            avGoalDiff = 0.144736842105263,
                            avblockedshots = 2.3947368421052602,
                            avconceded = 1.4736842105263199,
                            avdraws = 0.25,
                            avfreekicks = 16.407894736842099,
                            avgoalattempts = 11.289473684210501,
                            avgoals = 1.1447368421052599,
                            avloses = 0.44736842105263203,
                            avpossession = 47.460526315789501,
                            avshotsoffgoal = 4.8815789473684204,
                            avshotsongoal = 4.0131578947368398,
                            avwins = 0.30263157894736797
                        },
                        new
                        {
                            Id = 17,
                            AttackingRating = 77.0,
                            ClubWorth = 55.0,
                            DefenceDepth = 50.0,
                            DefenceRating = 76.0,
                            DefenceWidth = 40.0,
                            Dislikes = 10.0,
                            Likes = 48.0,
                            Matches_played = 227,
                            MidfieldRating = 77.0,
                            OffenceWidth = 70.0,
                            Overall = 77.0,
                            Teamname = "Granada_CF",
                            XIAverageAge = 27.09,
                            avGoalDiff = 0.48017621145374501,
                            avblockedshots = 2.5330396475770902,
                            avconceded = 1.6784140969162999,
                            avdraws = 0.22026431718061701,
                            avfreekicks = 15.7973568281938,
                            avgoalattempts = 10.568281938326001,
                            avgoals = 1.03964757709251,
                            avloses = 0.506607929515419,
                            avpossession = 44.748898678414101,
                            avshotsoffgoal = 4.6696035242290801,
                            avshotsongoal = 3.3656387665198202,
                            avwins = 0.27312775330396499
                        },
                        new
                        {
                            Id = 18,
                            AttackingRating = 73.0,
                            ClubWorth = 4.5,
                            DefenceDepth = 50.0,
                            DefenceRating = 73.0,
                            DefenceWidth = 60.0,
                            Dislikes = 6.0,
                            Likes = 22.0,
                            Matches_played = 76,
                            MidfieldRating = 73.0,
                            OffenceWidth = 60.0,
                            Overall = 73.0,
                            Teamname = "Huesca",
                            XIAverageAge = 27.18,
                            avGoalDiff = 0.27631578947368401,
                            avblockedshots = 2.5526315789473699,
                            avconceded = 1.5526315789473699,
                            avdraws = 0.32894736842105299,
                            avfreekicks = 16.105263157894701,
                            avgoalattempts = 11.592105263157899,
                            avgoals = 1.01315789473684,
                            avloses = 0.48684210526315802,
                            avpossession = 46.302631578947398,
                            avshotsoffgoal = 5.2763157894736796,
                            avshotsongoal = 3.7631578947368398,
                            avwins = 0.18421052631578899
                        },
                        new
                        {
                            Id = 19,
                            AttackingRating = 77.0,
                            ClubWorth = 38.0,
                            DefenceDepth = 47.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 38.0,
                            Dislikes = 8.0,
                            Likes = 48.0,
                            Matches_played = 114,
                            MidfieldRating = 74.0,
                            OffenceWidth = 55.0,
                            Overall = 75.0,
                            Teamname = "Las_Palmas",
                            XIAverageAge = 25.82,
                            avGoalDiff = 0.570175438596491,
                            avblockedshots = 2.2543859649122799,
                            avconceded = 1.76315789473684,
                            avdraws = 0.21052631578947401,
                            avfreekicks = 19.4385964912281,
                            avgoalattempts = 11.1140350877193,
                            avgoals = 1.0701754385964899,
                            avloses = 0.55263157894736903,
                            avpossession = 56.1929824561403,
                            avshotsoffgoal = 4.7105263157894699,
                            avshotsongoal = 4.1491228070175401,
                            avwins = 0.23684210526315799
                        },
                        new
                        {
                            Id = 20,
                            AttackingRating = 75.0,
                            ClubWorth = 10.800000000000001,
                            DefenceDepth = 70.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 40.0,
                            Dislikes = 11.0,
                            Likes = 27.0,
                            Matches_played = 151,
                            MidfieldRating = 75.0,
                            OffenceWidth = 70.0,
                            Overall = 75.0,
                            Teamname = "Leganes",
                            XIAverageAge = 27.640000000000001,
                            avGoalDiff = 0.34437086092715202,
                            avblockedshots = 2.4503311258278102,
                            avconceded = 1.32450331125828,
                            avdraws = 0.278145695364238,
                            avfreekicks = 14.9403973509934,
                            avgoalattempts = 10.9072847682119,
                            avgoals = 0.887417218543046,
                            avloses = 0.47019867549668898,
                            avpossession = 43.443708609271503,
                            avshotsoffgoal = 4.8675496688741697,
                            avshotsongoal = 3.5894039735099299,
                            avwins = 0.25165562913907302
                        },
                        new
                        {
                            Id = 21,
                            AttackingRating = 79.0,
                            ClubWorth = 49.0,
                            DefenceDepth = 60.0,
                            DefenceRating = 74.0,
                            DefenceWidth = 50.0,
                            Dislikes = 13.0,
                            Likes = 39.0,
                            Matches_played = 266,
                            MidfieldRating = 77.0,
                            OffenceWidth = 70.0,
                            Overall = 77.0,
                            Teamname = "Levante",
                            XIAverageAge = 28.27,
                            avGoalDiff = 0.360902255639098,
                            avblockedshots = 2.6052631578947398,
                            avconceded = 1.55639097744361,
                            avdraws = 0.28195488721804501,
                            avfreekicks = 15.451127819548899,
                            avgoalattempts = 10.7631578947368,
                            avgoals = 1.13533834586466,
                            avloses = 0.43984962406014999,
                            avpossession = 44.9962406015038,
                            avshotsoffgoal = 4.6654135338345899,
                            avshotsongoal = 3.4924812030075199,
                            avwins = 0.278195488721804
                        },
                        new
                        {
                            Id = 22,
                            AttackingRating = 75.0,
                            ClubWorth = 105.0,
                            DefenceDepth = 44.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 35.0,
                            Dislikes = 25.0,
                            Likes = 86.0,
                            Matches_played = 190,
                            MidfieldRating = 75.0,
                            OffenceWidth = 47.0,
                            Overall = 75.0,
                            Teamname = "Malaga",
                            XIAverageAge = 26.91,
                            avGoalDiff = 0.42631578947368398,
                            avblockedshots = 2.6421052631578901,
                            avconceded = 1.2894736842105301,
                            avdraws = 0.231578947368421,
                            avfreekicks = 16.378947368421102,
                            avgoalattempts = 12.0,
                            avgoals = 1.0105263157894699,
                            avloses = 0.47894736842105301,
                            avpossession = 47.994736842105297,
                            avshotsoffgoal = 5.2842105263157899,
                            avshotsongoal = 4.07368421052632,
                            avwins = 0.28947368421052599
                        },
                        new
                        {
                            Id = 23,
                            AttackingRating = 75.0,
                            ClubWorth = 6.7999999999999998,
                            DefenceDepth = 50.0,
                            DefenceRating = 73.0,
                            DefenceWidth = 50.0,
                            Dislikes = 14.0,
                            Likes = 49.0,
                            Matches_played = 38,
                            MidfieldRating = 74.0,
                            OffenceWidth = 60.0,
                            Overall = 74.0,
                            Teamname = "Mallorca",
                            XIAverageAge = 26.73,
                            avGoalDiff = 0.81578947368420995,
                            avblockedshots = 2.57894736842105,
                            avconceded = 1.7105263157894699,
                            avdraws = 0.157894736842105,
                            avfreekicks = 15.921052631579,
                            avgoalattempts = 11.0526315789474,
                            avgoals = 1.0526315789473699,
                            avloses = 0.60526315789473695,
                            avpossession = 44.552631578947398,
                            avshotsoffgoal = 5.0526315789473699,
                            avshotsongoal = 3.42105263157895,
                            avwins = 0.23684210526315799
                        },
                        new
                        {
                            Id = 24,
                            AttackingRating = 78.0,
                            ClubWorth = 15.0,
                            DefenceDepth = 70.0,
                            DefenceRating = 75.0,
                            DefenceWidth = 70.0,
                            Dislikes = 2.0,
                            Likes = 29.0,
                            Matches_played = 152,
                            MidfieldRating = 77.0,
                            OffenceWidth = 60.0,
                            Overall = 76.0,
                            Teamname = "Osasuna",
                            XIAverageAge = 27.82,
                            avGoalDiff = 0.33552631578947401,
                            avblockedshots = 2.3421052631578898,
                            avconceded = 1.6973684210526301,
                            avdraws = 0.28289473684210498,
                            avfreekicks = 14.8223684210526,
                            avgoalattempts = 10.967105263157899,
                            avgoals = 1.0197368421052599,
                            avloses = 0.46710526315789502,
                            avpossession = 44.052631578947398,
                            avshotsoffgoal = 4.9868421052631602,
                            avshotsongoal = 3.6381578947368398,
                            avwins = 0.25
                        },
                        new
                        {
                            Id = 25,
                            AttackingRating = 78.0,
                            ClubWorth = 10.0,
                            DefenceDepth = 70.0,
                            DefenceRating = 72.0,
                            DefenceWidth = 60.0,
                            Dislikes = 7.0,
                            Likes = 40.0,
                            Matches_played = 152,
                            MidfieldRating = 74.0,
                            OffenceWidth = 60.0,
                            Overall = 74.0,
                            Teamname = "Rayo_Vallecano",
                            XIAverageAge = 27.82,
                            avGoalDiff = 0.5,
                            avblockedshots = 3.0526315789473699,
                            avconceded = 1.9144736842105301,
                            avdraws = 0.177631578947368,
                            avfreekicks = 16.967105263157901,
                            avgoalattempts = 13.0592105263158,
                            avgoals = 1.21710526315789,
                            avloses = 0.52631578947368396,
                            avpossession = 55.210526315789501,
                            avshotsoffgoal = 5.5460526315789496,
                            avshotsongoal = 4.4605263157894699,
                            avwins = 0.29605263157894701
                        },
                        new
                        {
                            Id = 26,
                            AttackingRating = 83.0,
                            ClubWorth = 3100.0,
                            DefenceDepth = 80.0,
                            DefenceRating = 83.0,
                            DefenceWidth = 50.0,
                            Dislikes = 451.0,
                            Likes = 959.0,
                            Matches_played = 304,
                            MidfieldRating = 86.0,
                            OffenceWidth = 50.0,
                            Overall = 84.0,
                            Teamname = "Real_Madrid",
                            XIAverageAge = 28.09,
                            avGoalDiff = 0.38815789473684198,
                            avblockedshots = 3.5888157894736801,
                            avconceded = 0.96710526315789502,
                            avdraws = 0.17434210526315799,
                            avfreekicks = 15.1940789473684,
                            avgoalattempts = 17.1184210526316,
                            avgoals = 2.4078947368421102,
                            avloses = 0.14144736842105299,
                            avpossession = 58.661184210526301,
                            avshotsoffgoal = 6.7993421052631602,
                            avshotsongoal = 6.7302631578947398,
                            avwins = 0.68421052631579005
                        },
                        new
                        {
                            Id = 27,
                            AttackingRating = 82.0,
                            ClubWorth = 150.0,
                            DefenceDepth = 50.0,
                            DefenceRating = 77.0,
                            DefenceWidth = 40.0,
                            Dislikes = 31.0,
                            Likes = 146.0,
                            Matches_played = 304,
                            MidfieldRating = 80.0,
                            OffenceWidth = 60.0,
                            Overall = 80.0,
                            Teamname = "Real_Sociedad",
                            XIAverageAge = 25.18,
                            avGoalDiff = 0.41447368421052599,
                            avblockedshots = 2.8651315789473699,
                            avconceded = 1.30921052631579,
                            avdraws = 0.25328947368421101,
                            avfreekicks = 16.963815789473699,
                            avgoalattempts = 12.101973684210501,
                            avgoals = 1.43421052631579,
                            avloses = 0.355263157894737,
                            avpossession = 53.578947368421098,
                            avshotsoffgoal = 5.0855263157894699,
                            avshotsongoal = 4.1513157894736796,
                            avwins = 0.39144736842105299
                        },
                        new
                        {
                            Id = 28,
                            AttackingRating = 80.0,
                            ClubWorth = 540.0,
                            DefenceDepth = 70.0,
                            DefenceRating = 83.0,
                            DefenceWidth = 70.0,
                            Dislikes = 48.0,
                            Likes = 180.0,
                            Matches_played = 303,
                            MidfieldRating = 82.0,
                            OffenceWidth = 80.0,
                            Overall = 82.0,
                            Teamname = "Sevilla",
                            XIAverageAge = 28.640000000000001,
                            avGoalDiff = 0.57095709570957098,
                            avblockedshots = 2.8019801980198,
                            avconceded = 1.2046204620462,
                            avdraws = 0.224422442244224,
                            avfreekicks = 14.8448844884488,
                            avgoalattempts = 12.8844884488449,
                            avgoals = 1.57755775577558,
                            avloses = 0.27062706270627102,
                            avpossession = 54.174917491749198,
                            avshotsoffgoal = 5.4455445544554504,
                            avshotsongoal = 4.6369636963696399,
                            avwins = 0.50495049504950495
                        },
                        new
                        {
                            Id = 29,
                            AttackingRating = 77.0,
                            ClubWorth = 530.0,
                            DefenceDepth = 40.0,
                            DefenceRating = 78.0,
                            DefenceWidth = 40.0,
                            Dislikes = 45.0,
                            Likes = 248.0,
                            Matches_played = 304,
                            MidfieldRating = 77.0,
                            OffenceWidth = 40.0,
                            Overall = 78.0,
                            Teamname = "Valencia",
                            XIAverageAge = 26.82,
                            avGoalDiff = 0.47368421052631599,
                            avblockedshots = 2.5526315789473699,
                            avconceded = 1.2401315789473699,
                            avdraws = 0.28289473684210498,
                            avfreekicks = 17.023026315789501,
                            avgoalattempts = 11.519736842105299,
                            avgoals = 1.4309210526315801,
                            avloses = 0.32236842105263203,
                            avpossession = 49.368421052631597,
                            avshotsoffgoal = 4.8256578947368398,
                            avshotsongoal = 4.1414473684210504,
                            avwins = 0.394736842105263
                        },
                        new
                        {
                            Id = 30,
                            AttackingRating = 76.0,
                            ClubWorth = 8.9000000000000004,
                            DefenceDepth = 40.0,
                            DefenceRating = 74.0,
                            DefenceWidth = 40.0,
                            Dislikes = 11.0,
                            Likes = 43.0,
                            Matches_played = 152,
                            MidfieldRating = 76.0,
                            OffenceWidth = 60.0,
                            Overall = 75.0,
                            Teamname = "Valladolid",
                            XIAverageAge = 27.640000000000001,
                            avGoalDiff = 0.29605263157894701,
                            avblockedshots = 2.2171052631578898,
                            avconceded = 1.38815789473684,
                            avdraws = 0.375,
                            avfreekicks = 15.9868421052632,
                            avgoalattempts = 10.0592105263158,
                            avgoals = 0.89473684210526305,
                            avloses = 0.42105263157894701,
                            avpossession = 45.756578947368403,
                            avshotsoffgoal = 4.5394736842105301,
                            avshotsongoal = 3.3026315789473699,
                            avwins = 0.20394736842105299
                        },
                        new
                        {
                            Id = 31,
                            AttackingRating = 83.0,
                            ClubWorth = 370.0,
                            DefenceDepth = 50.0,
                            DefenceRating = 79.0,
                            DefenceWidth = 60.0,
                            Dislikes = 36.0,
                            Likes = 123.0,
                            Matches_played = 304,
                            MidfieldRating = 79.0,
                            OffenceWidth = 60.0,
                            Overall = 80.0,
                            Teamname = "Villarreal",
                            XIAverageAge = 27.09,
                            avGoalDiff = 0.292763157894737,
                            avblockedshots = 2.7269736842105301,
                            avconceded = 1.1315789473684199,
                            avdraws = 0.26315789473684198,
                            avfreekicks = 14.792763157894701,
                            avgoalattempts = 11.779605263157899,
                            avgoals = 1.4375,
                            avloses = 0.30592105263157898,
                            avpossession = 49.819078947368403,
                            avshotsoffgoal = 4.7138157894736796,
                            avshotsongoal = 4.3388157894736796,
                            avwins = 0.43092105263157898
                        });
                });

            modelBuilder.Entity("CollectorsApp.DAL.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CollectorsApp.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CollectorsApp.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectorsApp.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CollectorsApp.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
